version: '3'
services:
  kademlia-interactive:
    image: nettwerking_kademlia-interactive:latest
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "interactivenode.go", "--port", "7999", "--interactive", "true"]
    deploy:
      replicas: 1
  kademlia-follower:
    image: nettwerking_kademlia-follower:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "interactivenode.go", "--port", "7999",
      "--interactive", "false", "--id", "abcdef1234abcdef1234abcdef1234abcdef1234", "--addr", "10.0.0.2:7999"] # "10.0.0.2:7999" when using docker swarm
    depends_on:
      - kademlia-interactive
    deploy:
      replicas: 20
