title = "TOML Example"

[owner]
name = "Sir Donkey"
id = "5111111400000000000000000000000000000000"
created = 1979-05-27T07:32:00-08:00

[database]
server = "192.168.1.1"
port = [8001]

[clients] #The important thing is, even if contacts are not stored, the automatic ping will quickly reconstruct its neighbor list. This is due to the fact that everynode pings constantly to update and check if neighbors are still alive.
contacts = [["{192.199.10.10, 8002}"],
            ["{192.199.20.20, 8003}"],
            ["{192.199.23.11, 8005}"]]

[files]# A file is implemented here whenever the tree table is updated.
contents = []
